// Personalization stays local to this home page.
const paths={apps:'M5 5h.01M12 5h.01M19 5h.01M5 12h.01M12 12h.01M19 12h.01M5 19h.01M12 19h.01M19 19h.01',edit:'m16 3 5 5-13 13H3v-5L16 3ZM14 5l5 5',plus:'M12 5v14M5 12h14',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0V5ZM5 10v2a7 7 0 0 0 14 0v-2M12 19v3',lens:'M8 4H5a2 2 0 0 0-2 2v3m13-5h3a2 2 0 0 1 2 2v3M3 15v3a2 2 0 0 0 2 2h3m8 0h3a2 2 0 0 0 2-2v-3M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',ai:'M10 17a7 7 0 1 1 5-12M15 15l6 6M18 2v6m-3-3h6',close:'m6 6 12 12M18 6 6 18',sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z',device:'M3 4h18v13H3zM8 21h8m-4-4v4',image:'M3 3h18v18H3zM3 17l6-6 4 4 3-3 5 5M8 7h.01'};
function svg(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${name==='apps'?4:2}" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]}"/></svg>`}
const $=s=>document.querySelector(s);
$('#apps-toggle').innerHTML=svg('apps');$('#attach').innerHTML=svg('plus');$('#voice').innerHTML=svg('mic');$('#lens').innerHTML=svg('lens');$('#ai-mode').innerHTML=svg('ai')+'AI Mode';$('#customize').innerHTML=svg('edit')+'ปรับแต่งหน้าแรก';
document.body.insertAdjacentHTML('beforeend',`<aside id="apps-panel" class="floating-panel" aria-label="แอป Google" hidden><div class="apps-card"><h2 class="panel-heading">Your favorites<button id="edit-apps" class="icon-button" aria-label="แก้ไขแอปโปรด">${svg('edit')}</button></h2><div id="favorite-apps" class="apps-grid"></div></div><div id="other-apps" class="apps-grid"></div><p class="muted" id="apps-help" hidden>เลือกแอปเพื่อเพิ่มหรือนำออกจากรายการโปรด</p></aside><aside id="custom-panel" class="floating-panel" aria-label="ปรับแต่งหน้าแรก" hidden><h2 class="panel-heading">ปรับแต่งหน้าแรก<button id="close-custom" class="icon-button" aria-label="ปิด">${svg('close')}</button></h2><section class="settings-card"><h3>รูปลักษณ์</h3><div class="preview"><div class="mini-browser">${svg('device')}<div class="mini-bar"></div><strong>Google</strong></div></div><button id="background-upload" class="wide-button">${svg('image')}เปลี่ยนภาพพื้นหลัง</button><input type="file" id="background-file" accept="image/*" hidden><button class="text-button" id="clear-background">นำภาพพื้นหลังออก</button><div class="mode-group">${[['light','sun','Light'],['dark','moon','Dark'],['device','device','Device']].map(([v,i,t])=>`<button data-mode="${v}" aria-pressed="false">${svg(i)}${t}</button>`).join('')}</div><div class="colors"></div><label class="setting-row">สีที่กำหนดเอง<input id="custom-color" type="color" aria-label="เลือกสี"></label></section><section class="settings-card"><h3>แถบเครื่องมือ</h3><label class="setting-row">แสดงปุ่มค้นหาเพิ่มเติม<input id="show-tools" type="checkbox"></label></section><section class="settings-card"><h3>ทางลัด</h3><label class="setting-row">แสดงทางลัด<input id="show-shortcuts" type="checkbox"></label><button id="new-shortcut" class="wide-button">${svg('plus')}เพิ่มทางลัด</button><p class="muted">ทางลัดและค่าปรับแต่งจะบันทึกไว้ในเบราว์เซอร์นี้</p></section><button id="reset-look" class="text-button">คืนค่ารูปลักษณ์เริ่มต้น</button></aside><div id="status" class="status" role="status"></div>`);
let statusTimer;function notify(message){$('#status').textContent=t(message);clearTimeout(statusTimer);statusTimer=setTimeout(()=>$('#status').textContent='',6000)}
const preferenceKey='brave-home-appearance-v1';let prefs;try{prefs=JSON.parse(localStorage.getItem(preferenceKey))||{}}catch{prefs={}}if(!prefs||typeof prefs!=='object'||Array.isArray(prefs))prefs={};
const media=matchMedia('(prefers-color-scheme: dark)');
function applyPreferences(){const dark=prefs.mode==='dark'||(!['light','dark'].includes(prefs.mode)&&media.matches);document.body.classList.toggle('dark',dark);const color=/^#[0-9a-f]{6}$/i.test(prefs.color)?prefs.color:'#a8c7fa';document.documentElement.style.setProperty('--accent',color);const rgb=color.slice(1).match(/../g).map(x=>parseInt(x,16));document.documentElement.style.setProperty('--ink',rgb[0]*.299+rgb[1]*.587+rgb[2]*.114>145?'#17345c':'#ffffff');document.body.style.backgroundImage=prefs.background?`url("${prefs.background}")`:'';document.body.classList.toggle('has-background',!!prefs.background);$('#shortcuts').hidden=prefs.shortcuts===false;document.body.classList.toggle('hide-tools',prefs.tools===false);$('#show-shortcuts').checked=prefs.shortcuts!==false;$('#show-tools').checked=prefs.tools!==false;$('#custom-color').value=color;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===(prefs.mode||'device'))));document.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.color===color)));applyPersonalization()}
function persist(){applyPreferences();try{localStorage.setItem(preferenceKey,JSON.stringify(prefs))}catch{notify('บันทึกไม่ได้: พื้นที่จัดเก็บเต็มหรือเบราว์เซอร์ไม่อนุญาต')}}
media.addEventListener('change',applyPreferences);
const colors=['#a8c7fa','#c4c7c5','#8ab4f8','#bdc6dc','#b8cacc','#78d5c7','#a8d995','#c1c9b9','#e4cc6b','#ffb78e','#ddbeb0','#ffb2c6','#dfc1c5','#f3b2e8','#d3b7f7'];$('.colors').innerHTML=colors.map(c=>`<button class="swatch" data-color="${c}" style="--swatch:${c}" aria-label="สี ${c}" aria-pressed="false"><span></span></button>`).join('');document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{prefs.color=b.dataset.color;persist()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{prefs.mode=b.dataset.mode;persist()});$('#custom-color').oninput=e=>{prefs.color=e.target.value;persist()};$('#show-shortcuts').onchange=e=>{prefs.shortcuts=e.target.checked;persist()};$('#show-tools').onchange=e=>{prefs.tools=e.target.checked;persist()};$('#new-shortcut').onclick=()=>openEditor();$('#background-upload').onclick=()=>$('#background-file').click();$('#background-file').onchange=e=>uploadPersonalImage(e,'background');$('#clear-background').onclick=()=>{delete prefs.background;persist()};$('#reset-look').onclick=()=>{prefs={language:prefs.language};persist()};
function toggleCustom(open){$('#custom-panel').hidden=!open;document.body.classList.toggle('custom-open',open);$('#customize').setAttribute('aria-expanded',String(open));if(open){toggleApps(false);$('#close-custom').focus()}else $('#customize').focus()}
function toggleApps(open){$('#apps-panel').hidden=!open;$('#apps-toggle').setAttribute('aria-expanded',String(open))}
$('#customize').setAttribute('aria-controls','custom-panel');$('#customize').setAttribute('aria-expanded','false');$('#customize').onclick=()=>toggleCustom($('#custom-panel').hidden);$('#close-custom').onclick=()=>toggleCustom(false);$('#apps-toggle').onclick=()=>{const open=$('#apps-panel').hidden;toggleApps(open);if(open)$('#edit-apps').focus()};document.addEventListener('click',e=>{if(!e.composedPath().includes($('#apps-panel'))&&!e.composedPath().includes($('#apps-toggle')))toggleApps(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.open){if(!$('#apps-panel').hidden){toggleApps(false);$('#apps-toggle').focus()}else if(!$('#custom-panel').hidden)toggleCustom(false)}});
const apps=[['Account','myaccount.google.com'],['YouTube','www.youtube.com'],['Drive','drive.google.com'],['Maps','maps.google.com'],['Gmail','mail.google.com'],['Calendar','calendar.google.com'],['Translate','translate.google.com'],['Photos','photos.google.com'],['Vids','vids.google.com'],['Business','business.google.com'],['Gemini','gemini.google.com'],['Search','www.google.com'],['News','news.google.com'],['Meet','meet.google.com'],['Sheets','sheets.google.com'],['Docs','docs.google.com'],['Slides','slides.google.com'],['Keep','keep.google.com']];let favorites;try{favorites=JSON.parse(localStorage.getItem('brave-home-favorites-v1'))}catch{}if(!Array.isArray(favorites))favorites=apps.slice(0,9).map(a=>a[0]);let editingApps=false;
const productIcons={
Drive:'<path fill="#0f9d58" d="M18 4h14L14 36H0z"/><path fill="#ffcd40" d="M18 4h14l18 32H36z"/><path fill="#4285f4" d="M0 36h50l-7 12H7z"/>',
Gmail:'<path fill="#4285f4" d="M3 12h8v33H3z"/><path fill="#34a853" d="M39 12h8v33h-8z"/><path fill="#ea4335" d="M3 9h7l15 12L40 9h7v11L25 36 3 20z"/><path fill="#fbbc04" d="m39 15 8-6v15l-8 6z"/>',
Calendar:'<rect x="4" y="5" width="42" height="42" rx="6" fill="#4285f4"/><path fill="#a1c2fa" d="M4 5h42v10H4z"/><text x="25" y="37" font-size="25" text-anchor="middle" fill="white" font-family="Arial">31</text>',
Sheets:'<path fill="#0f9d58" d="M9 2h24l10 10v36H9z"/><path fill="#87ceac" d="M33 2v10h10z"/><path stroke="white" fill="none" stroke-width="2" d="M16 23h20v16H16zM16 31h20M24 23v16"/>',
Docs:'<path fill="#4285f4" d="M9 2h24l10 10v36H9z"/><path fill="#a1c2fa" d="M33 2v10h10z"/><path stroke="white" stroke-width="2" d="M16 24h20M16 30h20M16 36h16"/>',
Slides:'<path fill="#fbbc04" d="M9 2h24l10 10v36H9z"/><path fill="#ffe699" d="M33 2v10h10z"/><path stroke="white" fill="none" stroke-width="2" d="M16 23h20v15H16z"/>',
Vids:'<rect x="3" y="9" width="37" height="34" rx="8" fill="#b5b4ff"/><rect x="11" y="4" width="36" height="43" rx="9" fill="#7868ff"/><path fill="white" d="m24 16 14 10-14 10z"/>',
Business:'<rect x="6" y="15" width="38" height="30" rx="4" fill="#4285f4"/><path fill="#82b1ff" d="M7 4h36l5 17H2z"/><path fill="#4b65bd" d="M16 4h8v17h-8zM33 4h10l5 17H35z"/><text x="30" y="39" font-family="Arial" font-size="20" fill="white">G</text>'};
function favicon(host,label){const img=document.createElement('img');img.alt='';if(productIcons[label]){img.src='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">'+productIcons[label]+'</svg>');return img}img.src='https://www.google.com/s2/favicons?domain='+encodeURIComponent(host)+'&sz=64';img.onerror=()=>{const fallback=document.createElement('span');fallback.textContent=label.slice(0,1);fallback.style.cssText='font-size:28px;color:#4285f4';img.replaceWith(fallback)};return img}
function renderApps(){for(const id of ['#favorite-apps','#other-apps'])$(id).replaceChildren();apps.forEach(([name,host])=>{const favorite=favorites.includes(name);const el=document.createElement(editingApps?'button':'a');el.className='app-link';if(editingApps){el.setAttribute('aria-pressed',String(favorite));el.onclick=()=>{favorites=favorite?favorites.filter(n=>n!==name):[...favorites,name];try{localStorage.setItem('brave-home-favorites-v1',JSON.stringify(favorites))}catch{notify('บันทึกแอปโปรดไม่ได้')}renderApps()}}else el.href='https://'+host+'/';const label=document.createElement('span');label.textContent=name;el.append(favicon(host,name),label);if(editingApps){const marker=document.createElement('small');marker.textContent=favorite?'✓ '+t('รายการโปรด'):'+ '+t('เพิ่ม');el.append(marker)}$(favorite?'#favorite-apps':'#other-apps').append(el)})}
$('#edit-apps').onclick=()=>{editingApps=!editingApps;$('#edit-apps').innerHTML=svg(editingApps?'close':'edit');$('#edit-apps').setAttribute('aria-label',editingApps?t('เสร็จสิ้นการแก้ไข'):t('แก้ไขแอปโปรด'));$('#apps-help').hidden=!editingApps;renderApps()};
function upgradeShortcuts(){document.querySelectorAll('.tile>a').forEach(a=>{const icon=a.querySelector('.icon');icon.replaceChildren(favicon(new URL(a.href).hostname,a.textContent.trim()))})}new MutationObserver(upgradeShortcuts).observe(list,{childList:true});upgradeShortcuts();
$('#attach').onclick=()=>location.assign('https://lens.google/');$('#ai-mode').onclick=()=>location.assign('https://www.google.com/search?udm=50&q='+encodeURIComponent(query.value.trim()));
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition, listening=false;
$('#voice').onclick=()=>{if(!Recognition){notify('เบราว์เซอร์นี้ไม่รองรับค้นหาด้วยเสียง ลองใช้ Chrome หรือพิมพ์คำค้น');return}if(listening){recognition.stop();return}recognition=new Recognition();recognition.lang=currentLanguage();recognition.interimResults=false;recognition.onstart=()=>{listening=true;$('#voice').setAttribute('aria-pressed','true');notify('กำลังฟัง… กดไมโครโฟนอีกครั้งเพื่อหยุด')};recognition.onresult=e=>{query.value=e.results[0][0].transcript;searchForm.requestSubmit()};recognition.onerror=e=>notify(e.error==='not-allowed'?'กรุณาอนุญาตไมโครโฟนในเบราว์เซอร์':'รับเสียงไม่ได้ กรุณาลองอีกครั้งหรือพิมพ์คำค้น');recognition.onend=()=>{listening=false;$('#voice').setAttribute('aria-pressed','false')};try{recognition.start()}catch{notify('เริ่มไมโครโฟนไม่ได้ กรุณาลองใหม่')}};
initializePersonalization();applyPreferences();renderApps();
