// Search providers and draft-only appearance previews.
const extraMessages=[
['เครื่องมือค้นหา','Search engine'],['ไอคอนเครื่องมือค้นหา','Search engine icon'],['ใช้ไอคอนดั้งเดิม','Use original icon'],['เปลี่ยนไอคอน','Change icon'],['แสดงไอคอนในช่องค้นหา','Show icon in search bar'],['ตัวเลือกสี','Color picker'],['เฉดสี','Hue'],['ความเข้มสี','Saturation'],['ความสว่าง','Lightness'],['ดูตัวอย่าง','Preview'],['ใช้แบบดั้งเดิม','Use original'],['เพิ่มรูป','Add image'],['ใช้รูปนี้','Use this image'],['รูปภาพ','Images'],['เพิ่มไฟล์','Add files'],['สร้างรูปภาพ','Create images'],['เครื่องมือ','Tools'],['ไฟล์ที่เลือกจะแสดงตัวอย่างในเครื่องเท่านั้น หากต้องการค้นหาหรือวิเคราะห์ ให้เปิดบริการแล้วแนบไฟล์ที่นั่น','Selected files are previewed locally only. Open a service and attach them there to search or analyze.'],['เปิด Google Lens','Open Google Lens'],['เปิด Gemini','Open Gemini'],['นำออก','Remove'],['ค้นหาด้วย','Search with'],['คำแนะนำจาก Google ใช้เมื่อเลือก Google เท่านั้น','Google suggestions are used only when Google is selected.'],['รูปใหม่ยังไม่ถูกบันทึก กดใช้รูปนี้เพื่อยืนยัน','This image is a draft. Choose Use this image to save.']];
for(const [th,en] of extraMessages)messages[th]={th,en,ja:en,zh:en};
const extraLocales=[
['เครื่องมือค้นหา','検索エンジン','搜索引擎'],['ไอคอนเครื่องมือค้นหา','検索エンジンのアイコン','搜索引擎图标'],['ใช้ไอคอนดั้งเดิม','元のアイコンを使用','使用默认图标'],['เปลี่ยนไอคอน','アイコンを変更','更换图标'],['แสดงไอคอนในช่องค้นหา','検索欄にアイコンを表示','在搜索栏显示图标'],['ตัวเลือกสี','カラーピッカー','颜色选择器'],['เฉดสี','色相','色相'],['ความเข้มสี','彩度','饱和度'],['ความสว่าง','明度','亮度'],['ดูตัวอย่าง','プレビュー','预览'],['ใช้แบบดั้งเดิม','元の設定を使用','使用默认样式'],['เพิ่มรูป','画像を追加','添加图片'],['ใช้รูปนี้','この画像を使用','使用此图片'],['รูปภาพ','画像','图片'],['เพิ่มไฟล์','ファイルを追加','添加文件'],['สร้างรูปภาพ','画像を生成','生成图片'],['เครื่องมือ','ツール','工具'],['ไฟล์ที่เลือกจะแสดงตัวอย่างในเครื่องเท่านั้น หากต้องการค้นหาหรือวิเคราะห์ ให้เปิดบริการแล้วแนบไฟล์ที่นั่น','選択したファイルは端末内でのみプレビューされます。検索・分析するにはサービスを開き、そこで添付してください。','所选文件仅在本机预览。如需搜索或分析，请打开相应服务并在那里上传文件。'],['เปิด Google Lens','Google Lens を開く','打开 Google Lens'],['เปิด Gemini','Gemini を開く','打开 Gemini'],['นำออก','削除','移除'],['ค้นหาด้วย','検索エンジン：','搜索引擎：'],['คำแนะนำจาก Google ใช้เมื่อเลือก Google เท่านั้น','Google の検索候補は Google 選択時のみ使用します。','仅在选择 Google 时使用 Google 搜索建议。'],['รูปใหม่ยังไม่ถูกบันทึก กดใช้รูปนี้เพื่อยืนยัน','画像はまだ保存されていません。「この画像を使用」で保存します。','新图片尚未保存，点击“使用此图片”确认。']];
for(const [key,ja,zh] of extraLocales)Object.assign(messages[key],{ja,zh});
const engines={google:{name:'Google',host:'www.google.com',action:'https://www.google.com/search',param:'q'},bing:{name:'Bing',host:'www.bing.com',action:'https://www.bing.com/search',param:'q'},duckduckgo:{name:'DuckDuckGo',host:'duckduckgo.com',action:'https://duckduckgo.com/',param:'q'},brave:{name:'Brave Search',host:'search.brave.com',action:'https://search.brave.com/search',param:'q'},yahoo:{name:'Yahoo',host:'search.yahoo.com',action:'https://search.yahoo.com/search',param:'p'}};
function activeEngine(){return engines[prefs.engine]||engines.google}
const searchSettings=document.createElement('section');searchSettings.className='settings-card';searchSettings.innerHTML='<h3>เครื่องมือค้นหา</h3><select id="engine-select" aria-label="เครื่องมือค้นหา">'+Object.entries(engines).map(([id,e])=>`<option value="${id}">${e.name}</option>`).join('')+'</select><label class="setting-row">แสดงไอคอนในช่องค้นหา<input id="engine-icon-toggle" type="checkbox"></label><button id="engine-icon-edit" class="wide-button">'+svg('image')+'เปลี่ยนไอคอน</button><p class="muted">คำแนะนำจาก Google ใช้เมื่อเลือก Google เท่านั้น</p>';
$('.advanced').before(searchSettings);
const engineBadge=document.createElement('span');engineBadge.id='engine-badge';engineBadge.setAttribute('aria-hidden','true');$('#attach').after(engineBadge);
document.body.insertAdjacentHTML('beforeend',`<dialog id="image-editor" class="image-editor"><h2 id="image-title"></h2><div class="image-options"><button id="image-original" class="image-option"><span id="original-preview"></span><span>ใช้แบบดั้งเดิม</span></button><button id="image-upload" class="image-option"><span class="upload-plus">+</span><span>เพิ่มรูป</span></button></div><div id="image-stage"></div><p class="muted">รูปใหม่ยังไม่ถูกบันทึก กดใช้รูปนี้เพื่อยืนยัน</p><input id="draft-image-file" type="file" accept="image/*" hidden><div class="actions"><button id="image-cancel">ยกเลิก</button><button id="image-apply" class="primary">ใช้รูปนี้</button></div></dialog><dialog id="color-editor"><h2 class="panel-heading"><span>ตัวเลือกสี</span><button id="color-close" class="icon-button" aria-label="ปิด">${svg('close')}</button></h2><label>เฉดสี<input id="hue-slider" class="hue-slider" type="range" min="0" max="360" value="210"></label><label>ความเข้มสี<input id="saturation-slider" type="range" min="0" max="100" value="80"></label><label>ความสว่าง<input id="lightness-slider" type="range" min="10" max="90" value="75"></label><div class="color-value"><span id="color-sample"></span><input id="hex-color" aria-label="สีที่กำหนดเอง" maxlength="7"></div><div class="actions"><button id="color-cancel">ยกเลิก</button><button id="color-apply" class="primary">บันทึก</button></div></dialog><div id="add-menu" hidden><button id="attach-images">${svg('image')}<span>เพิ่มรูป</span></button><button id="attach-files">${svg('plus')}<span>เพิ่มไฟล์</span></button><hr><h3>เครื่องมือ</h3><a href="https://gemini.google.com/" target="_blank" rel="noopener">${svg('ai')}<span>สร้างรูปภาพ</span></a></div><input id="attachment-file" type="file" multiple hidden><dialog id="attachment-preview"><h2>ดูตัวอย่าง</h2><div id="attachment-list"></div><p class="muted">ไฟล์ที่เลือกจะแสดงตัวอย่างในเครื่องเท่านั้น หากต้องการค้นหาหรือวิเคราะห์ ให้เปิดบริการแล้วแนบไฟล์ที่นั่น</p><div class="attachment-links"><a href="https://lens.google/" target="_blank" rel="noopener">เปิด Google Lens</a><a href="https://gemini.google.com/" target="_blank" rel="noopener">เปิด Gemini</a></div><div class="actions"><button id="attachments-close">ปิด</button></div></dialog>`);
$('.search-wrap').append($('#add-menu'));
$('#attach').setAttribute('aria-controls','add-menu');$('#attach').setAttribute('aria-expanded','false');
function setAddMenu(open){$('#add-menu').hidden=!open;$('#attach').setAttribute('aria-expanded',String(open));if(open){hideSuggestions();$('#attach-images').focus()}}
$('#attach').onclick=()=>setAddMenu($('#add-menu').hidden);
document.addEventListener('click',e=>{if(!e.composedPath().includes($('#add-menu'))&&!e.composedPath().includes($('#attach')))setAddMenu(false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#add-menu').hidden){setAddMenu(false);$('#attach').focus()}});
let attachmentURLs=[];
function clearAttachments(){attachmentURLs.forEach(url=>URL.revokeObjectURL(url));attachmentURLs=[];$('#attachment-list').replaceChildren()}
function selectAttachments(images){$('#attachment-file').accept=images?'image/*':'';setAddMenu(false);$('#attachment-file').click()}
$('#attach-images').onclick=()=>selectAttachments(true);$('#attach-files').onclick=()=>selectAttachments(false);
$('#attachment-file').onchange=e=>{const files=[...e.target.files];e.target.value='';if(!files.length)return;clearAttachments();files.forEach(file=>{const row=document.createElement('div');row.className='attachment-row';if(file.type.startsWith('image/')){const img=new Image();const url=URL.createObjectURL(file);attachmentURLs.push(url);img.src=url;img.alt='';row.append(img)}const name=document.createElement('span');name.textContent=file.name+' ('+Math.ceil(file.size/1024)+' KB)';row.append(name);$('#attachment-list').append(row)});translateUI();$('#attachment-preview').showModal()};
$('#attachments-close').onclick=()=>$('#attachment-preview').close();$('#attachment-preview').addEventListener('close',clearAttachments);
let draftField='logo',draftImage=null,uploadSequence=0;
function paintImageDraft(){const original=$('#original-preview');original.replaceChildren();if(draftField==='logo')original.textContent='Google';else if(draftField==='background'){original.className='original-background';original.textContent='Aa'}else original.append(favicon(activeEngine().host,activeEngine().name));
 const stage=$('#image-stage');stage.className=draftField==='background'?'background-stage':'';stage.replaceChildren();if(draftImage){const img=new Image();img.src=draftImage;img.alt=t('ดูตัวอย่าง');stage.append(img)}else{const label=document.createElement('strong');label.textContent=draftField==='logo'?'Google':draftField==='background'?t('ใช้แบบดั้งเดิม'):activeEngine().name;stage.append(label)}$('#image-original').setAttribute('aria-pressed',String(!draftImage));}
function openImageEditor(field){draftField=field;draftImage=prefs[field]||null;uploadSequence++;$('#image-title').textContent=t(field==='logo'?'โลโก้ที่กำหนดเอง':field==='background'?'เปลี่ยนภาพพื้นหลัง':'ไอคอนเครื่องมือค้นหา');paintImageDraft();translateUI();$('#image-editor').showModal()}
$('#logo-upload').onclick=()=>openImageEditor('logo');$('#background-upload').onclick=()=>openImageEditor('background');$('#engine-icon-edit').onclick=()=>openImageEditor('engineIcon');
$('#image-original').onclick=()=>{uploadSequence++;draftImage=null;paintImageDraft()};$('#image-upload').onclick=()=>$('#draft-image-file').click();$('#image-cancel').onclick=()=>$('#image-editor').close();$('#image-editor').addEventListener('close',()=>{uploadSequence++;draftImage=null});
$('#draft-image-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(!file.type.startsWith('image/'))return notify('กรุณาเลือกไฟล์รูปภาพ');if(file.size>3*1024*1024)return notify('กรุณาเลือกรูปขนาดไม่เกิน 3 MB');const sequence=++uploadSequence;try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});const img=new Image();img.src=data;await img.decode();if(sequence!==uploadSequence||!$('#image-editor').open)return;draftImage=data;paintImageDraft()}catch{notify('อ่านรูปภาพไม่ได้')}};
$('#image-apply').onclick=()=>{const next={...prefs};if(draftImage)next[draftField]=draftImage;else delete next[draftField];try{localStorage.setItem(preferenceKey,JSON.stringify(next))}catch{return notify('บันทึกไม่ได้: พื้นที่จัดเก็บเต็มหรือเบราว์เซอร์ไม่อนุญาต')}prefs=next;applyPreferences();$('#image-editor').close()};
const oldApplyPersonalization=applyPersonalization;applyPersonalization=function(){oldApplyPersonalization();applySearchEngine()};
function applySearchEngine(){const engine=activeEngine();$('#engine-select').value=prefs.engine in engines?prefs.engine:'google';$('#engine-icon-toggle').checked=prefs.showEngineIcon!==false;searchForm.action=engine.action;query.name=engine.param;query.placeholder=t('ค้นหาด้วย')+' '+engine.name;query.setAttribute('aria-label',query.placeholder);engineBadge.replaceChildren();if(prefs.engineIcon){const img=new Image();img.src=prefs.engineIcon;img.alt='';engineBadge.append(img)}else engineBadge.append(favicon(engine.host,engine.name));engineBadge.hidden=prefs.showEngineIcon===false;$('#attach').setAttribute('aria-label',t('เพิ่ม'));translateUI();query.placeholder=t('ค้นหาด้วย')+' '+engine.name;query.setAttribute('aria-label',query.placeholder);$('#attach').setAttribute('aria-label',t('เพิ่ม'));}
$('#engine-select').onchange=e=>{prefs.engine=e.target.value;clearTimeout(timer);request++;hideSuggestions();persist()};$('#engine-icon-toggle').onchange=e=>{prefs.showEngineIcon=e.target.checked;persist()};
const googleSuggestions=loadSuggestions;loadSuggestions=function(){if(activeEngine()!==engines.google){request++;hideSuggestions();return}googleSuggestions()};
let draftColor='#a8c7fa';
function hslHex(h,s,l){s/=100;l/=100;const a=s*Math.min(l,1-l);const f=n=>{const k=(n+h/30)%12;return Math.round(255*(l-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0')};return '#'+f(0)+f(8)+f(4)}
function setColorDraft(color){draftColor=color;$('#hex-color').value=color;$('#color-sample').style.background=color;$('#hex-color').setCustomValidity('')}
function syncSliders(hex){const [r,g,b]=hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255);const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;let h=0;if(d)h=max===r?((g-b)/d)%6:max===g?(b-r)/d+2:(r-g)/d+4;$('#hue-slider').value=(h*60+360)%360;$('#saturation-slider').value=d?100*d/(1-Math.abs(2*l-1)):0;$('#lightness-slider').value=l*100}
const colorButton=document.createElement('button');colorButton.id='open-color-picker';colorButton.className='swatch';colorButton.innerHTML=svg('edit');colorButton.setAttribute('aria-label',t('ตัวเลือกสี'));$('.colors').append(colorButton);
colorButton.onclick=()=>{setColorDraft(prefs.color||'#a8c7fa');syncSliders(draftColor);translateUI();$('#color-editor').showModal()};$('#custom-color').parentElement.hidden=true;
for(const id of ['#hue-slider','#saturation-slider','#lightness-slider'])$(id).oninput=()=>setColorDraft(hslHex(+$('#hue-slider').value,+$('#saturation-slider').value,+$('#lightness-slider').value));
$('#hex-color').oninput=e=>{if(/^#[0-9a-f]{6}$/i.test(e.target.value)){setColorDraft(e.target.value);syncSliders(draftColor)}else e.target.setCustomValidity(t('เลือกสี'))};$('#color-apply').onclick=()=>{if(!$('#hex-color').reportValidity())return;prefs.color=draftColor;persist();$('#color-editor').close()};$('#color-close').onclick=$('#color-cancel').onclick=()=>$('#color-editor').close();
applySearchEngine();
